### ISSUE TITLE
error running htseq-count

### ISSUE THREAD

**Issue by dstern** [htseq/htseq#13]
I have installed htseq from github repo.
When I run htseq-count, get following error. 

Here's example call:
htseq-count -i gene_id --stranded=no -f bam -t exon  catrim.Sample_Cnek_F_Car_10.bam augustus.exon.gtf > catrim.Sample_Cnek_F_Car_10.bam.counts

Here's error:
  <built-in function delete__Pair_int_obj> returned a result with an error set
  [Exception type: SystemError, raised in _HTSeq_internal.py:33]

Error is a bit mysterious to me, so having trouble determining whether this is software or input error.
Thanks!
David

**Comment by dstern** [comment]
Note, this appears to be a problem with HTSeq-0.13.0
I removed and installed HTSeq-0.12.4 and everything running fine now.

**Comment by iosonofabio** [comment]
Hi @dstern 

Can you please provide your GTF and BAM files online so I can test HTSeq on them?

**Comment by wzthhm** [comment]
I also meet the same problem(┬_┬)

**Comment by iosonofabio** [comment]
I finally had time to go through this. Turns out the files you shared @dstern were not the same as the ones above. Nonetheless, I ran the latest HTSeq from master on them and could process the first 17 million reads without any issue. At that point, I stopped because I have no time to go through such huge datasets for each bugfix.

I'll therefore close this issue.

I recommend you try the latest version from master and if you (or @wzthhm) still face this problem, please make a minimal file with less than a million reads which still has the problem and reopen this issue with a link to it and the exact command you ran.

Thanks!
