### ISSUE TITLE
Problem with htseq-count using the coordinate-sorted BAM files with -r pos option

### ISSUE THREAD

**Issue by EngineerReversed** [htseq/htseq#18]
`STAR` released a flag option `--quantMode` for gene to read mapping count. The author claim to give similar results as of `htseq-count` with default parameters of `STAR`.

However, when I tried comparing results with **coordinate-sorted BAM** files, the results are dissimilar. Here is a full thread on this topic: [Link](https://github.com/alexdobin/STAR/issues/974)

Why are the results different? Is there some problem with `htseq-count` for *coordinate-sorted BAM* files?

Tool versions:
* STAR=**2.7.5c**
* htseq=**0.11.0**

**Comment by iosonofabio** [comment]
Hi @EngineerReversed and thanks for the report. There is a long standing quasi-bug with coordinate sorted files. Since you provided the FASTQ and GTF files in this case, let me have a look at see if I can track down the problem.

In any case it seems safe to say that for **unsorted BAM** files, `htseq-count` and `STAR` are in perfect agreement.

**Comment by iosonofabio** [comment]
I tested this as shown in the STAR thread referenced, and find that results are consistent and expected. Closing.
