### ISSUE TITLE
Does HTSeq  generate transcript counts?

### ISSUE THREAD

**Issue by paolabc** [htseq/htseq#59]
Hi there!

I used htseq-count and I received back different read count results for two transcript that fall in the same gene.

 I used gene_id as in -i parameter (GFF attribute to be used as feature ID). I belived it will detect that the gene ID from different transcript are from the same gene, thus it will join the read count amount of these transcript to gave just one count for a given gene. So I asked: Is  it a expected result ? If not, is there a parameter that I should set?

Thanks in advance for your help!

**Comment by iosonofabio** [comment]
htseq-count counts exon by exon. However, the default option is to aggregate the counts from all exons with the same geneid into one single number.

You can change this - as you found out - by the -i flag. e.g. for disaggregated exon-level counts you might use -i gene_id -i exon_number -i exon_id. Then each row of your output will be a unique combo of those three elements.

Note that when counting at the exon level, multimappers become very common because exons often overlap. So you might want to experiment a little with those flags as well.
